apiVersion: apps/v1
kind: Deployment

metadata:
  name: alert-service
  namespace: hackathon

spec:
  replicas: 2

  selector:
    matchLabels:
      app: alert-service

  template:
    metadata:
      labels:
        app: alert-service

    spec:
      containers:
      - name: alert-service
        image: 784369107852.dkr.ecr.ap-south-1.amazonaws.com/alert-service:v1

        imagePullPolicy: Always

        ports:
        - containerPort: 8091

        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_HOST

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_NAME

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
