apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: hackathon
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: hackathon
  MYSQL_USER: admin
  MYSQL_PASSWORD: Admin@123

  DB_HOST: mysql
  DB_NAME: hackathon
  DB_USER: admin
  DB_PASSWORD: Admin@123
