pipeline {
    agent any

    environment {
        AWS_ACCOUNT_ID = "784369107852"
        AWS_REGION     = "ap-south-1"
        ECR_REPO       = "alert-service"
        IMAGE_TAG      = "${BUILD_NUMBER}"

        IMAGE = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Jar') {
            steps {
                dir('backend_java/alert-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend_java/alert-service') {
                    sh """
                        docker build -t ${IMAGE} .
                    """
                }
            }
        }

        stage('Login to ECR') {
            steps {
                sh """
                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login \
                --username AWS \
                --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                """
            }
        }

        stage('Push Docker Image') {
            steps {
                sh """
                docker push ${IMAGE}
                """
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh """
                aws eks update-kubeconfig \
                --region ${AWS_REGION} \
                --name YOUR_CLUSTER_NAME

                kubectl set image deployment/alert-service \
                alert-service=${IMAGE}

                kubectl rollout status deployment/alert-service
                """
            }
        }

    }
}
