pipeline {
    agent any

    environment {
        AWS_ACCOUNT_ID = '784369107852'
        AWS_REGION     = 'ap-south-1'
        ECR_REPO       = 'alert-service'
        IMAGE_TAG      = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }


        stage('Build Maven') {
            steps {
                dir('backend_java/alert-service') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend_java/alert-service') {
                    sh """
                    docker build \
                    -t ${ECR_REPO}:${IMAGE_TAG} .
                    """
                }
            }
        }

        stage('Login ECR') {
            steps {
                sh """
                aws ecr get-login-password --region ${AWS_REGION} | \
                docker login --username AWS --password-stdin \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                """
            }
        }

        stage('Push Image') {
            steps {
                sh """
                docker tag ${ECR_REPO}:${IMAGE_TAG} \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}

                docker push \
                ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}
                """
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh """
                kubectl apply -f database/mysql-secret.yaml

                kubectl apply -f database/mysql-pvc.yaml
                kubectl apply -f database/mysql-deployment.yaml
                kubectl apply -f database/mysql-service.yaml

                kubectl apply -f k8s/alert-service/deployment.yaml
                kubectl apply -f k8s/alert-service/service.yaml
                """
            }
        }
    }
}
